spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dummy
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000 # 30 sec
      maximum-pool-size: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # spring start without db
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

openai:
  apiKey:
